export const todayPageText = {
  productName: 'CHECKLIST RESTAURANTE',
  title: 'Tarefas de hoje',
  dateBadge: '31 AGO',
  summaryTitle: 'Progresso de hoje',
  doneLabel: 'feitas',
  pendingLabel: 'pendentes',
  notDoneLabel: 'não feita',
  filterAriaLabel: 'Filtrar tarefas',
  myTasksTab: 'Minhas',
  generalTasksTab: 'Gerais',
  allTasksTab: 'Todas',
  pendingTaskStatus: 'Pendente',
  pendingTasksSuffix: 'tarefas pendentes',
  assigneePrefix: 'Responsável:',
  currentUserLabel: 'Você',
  evidenceIcon: '▣',
  navigationAriaLabel: 'Navegação principal',
  todayNavigationLabel: 'Hoje',
  todayNavigationIcon: '▣',
  historyNavigationLabel: 'Histórico',
  historyNavigationIcon: '◷',
  moreNavigationLabel: 'Mais',
  moreNavigationIcon: '☰',
} as const
